spring:
  datasource:
    url: jdbc:mysql://localhost:3304/test?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: r1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never

